FROM node:20

WORKER /app

COPY . .

RUN npm install
RUN npm run build
RUN npx primsa generate

EXPOSE 3000

CMD ["node", "dist/index.js"]

# Base layer
FROM ubuntu:20.04

# Instruction layer 1
RUN apt-get update && apt-get install -y python3

# Instruction layer 2
COPY . /app

# Instruction layer 3
RUN pip3 install -r /app/requirements.txt